const careerDatabase = [
    {
        id: 1,
        title: "Data Scientist",
        category: "Technology",
        match: 0, // Will be calculated
        description: "Data scientists analyze and interpret complex data to help organizations make informed decisions. They use statistical techniques, machine learning, and data visualization tools.",
        salary: "$95,000 - $165,000",
        growth: "31% (Much faster than average)",
        education: "Bachelor's in Data Science, Computer Science, or related field",
        skills: ["Programming", "Data Analysis", "Statistics", "Machine Learning", "Problem Solving", "Critical Thinking"],
        interests: ["Technology", "Analytics", "Research", "Mathematics"],
        minEducation: "bachelor",
        experienceLevel: "mid",
        workEnvironment: ["office", "remote", "hybrid"],
        salaryRange: "senior"
    },
    {
        id: 2,
        title: "UX/UI Designer",
        category: "Design",
        match: 0,
        description: "UX/UI designers create engaging and intuitive user experiences for digital products. They conduct user research, design interfaces, and test usability.",
        salary: "$75,000 - $130,000",
        growth: "13% (Faster than average)",
        education: "Bachelor's in Design, HCI, or related field",
        skills: ["Design", "Creativity", "User Research", "Prototyping", "Communication", "Problem Solving"],
        interests: ["Design", "Technology", "Psychology", "Arts"],
        minEducation: "bachelor",
        experienceLevel: "mid",
        workEnvironment: ["office", "remote", "hybrid"],
        salaryRange: "mid"
    },
    {
        id: 3,
        title: "Software Engineer",
        category: "Technology",
        match: 0,
        description: "Software engineers design, develop, and maintain software applications. They work across various industries to create solutions for specific needs.",
        salary: "$85,000 - $160,000",
        growth: "22% (Much faster than average)",
        education: "Bachelor's in Computer Science or related field",
        skills: ["Programming", "Problem Solving", "Algorithms", "Software Development", "Teamwork", "Critical Thinking"],
        interests: ["Technology", "Engineering", "Problem Solving", "Mathematics"],
        minEducation: "bachelor",
        experienceLevel: "mid",
        workEnvironment: ["office", "remote", "hybrid"],
        salaryRange: "senior"
    },
    {
        id: 4,
        title: "Digital Marketing Manager",
        category: "Marketing",
        match: 0,
        description: "Digital marketing managers develop and implement online marketing strategies to promote brands, products, and services across digital channels.",
        salary: "$70,000 - $130,000",
        growth: "10% (Faster than average)",
        education: "Bachelor's in Marketing, Business, or related field",
        skills: ["Marketing", "Analytics", "Communication", "Strategy", "Creativity", "Leadership"],
        interests: ["Marketing", "Business", "Analytics", "Sales"],
        minEducation: "bachelor",
        experienceLevel: "mid",
        workEnvironment: ["office", "remote", "hybrid"],
        salaryRange: "mid"
    },
    {
        id: 5,
        title: "Product Manager",
        category: "Business",
        match: 0,
        description: "Product managers guide the success of a product and lead the cross-functional team that is responsible for improving it.",
        salary: "$90,000 - $160,000",
        growth: "10% (Faster than average)",
        education: "Bachelor's in Business, Computer Science, or related field",
        skills: ["Leadership", "Communication", "Strategy", "Problem Solving", "Analytics", "Teamwork"],
        interests: ["Business", "Technology", "Management", "Strategy"],
        minEducation: "bachelor",
        experienceLevel: "mid",
        workEnvironment: ["office", "hybrid"],
        salaryRange: "senior"
    },
    {
        id: 6,
        title: "Healthcare Administrator",
        category: "Healthcare",
        match: 0,
        description: "Healthcare administrators plan, direct, and coordinate medical and health services in various healthcare settings.",
        salary: "$65,000 - $150,000",
        growth: "28% (Much faster than average)",
        education: "Bachelor's in Health Administration or related field",
        skills: ["Leadership", "Communication", "Management", "Problem Solving", "Analytics"],
        interests: ["Healthcare", "Management", "Business"],
        minEducation: "bachelor",
        experienceLevel: "mid",
        workEnvironment: ["office"],
        salaryRange: "mid"
    },
    {
        id: 7,
        title: "Financial Analyst",
        category: "Finance",
        match: 0,
        description: "Financial analysts provide guidance to businesses and individuals making investment decisions.",
        salary: "$60,000 - $120,000",
        growth: "6% (As fast as average)",
        education: "Bachelor's in Finance, Economics, or related field",
        skills: ["Analytics", "Finance", "Problem Solving", "Communication", "Critical Thinking"],
        interests: ["Finance", "Analytics", "Business", "Mathematics"],
        minEducation: "bachelor",
        experienceLevel: "mid",
        workEnvironment: ["office"],
        salaryRange: "mid"
    },
    {
        id: 8,
        title: "Cybersecurity Analyst",
        category: "Technology",
        match: 0,
        description: "Cybersecurity analysts protect organizations' computer systems and networks from cyber threats.",
        salary: "$80,000 - $140,000",
        growth: "33% (Much faster than average)",
        education: "Bachelor's in Cybersecurity, Computer Science, or related field",
        skills: ["Programming", "Problem Solving", "Analytics", "Critical Thinking", "Communication"],
        interests: ["Technology", "Security", "Problem Solving", "Analytics"],
        minEducation: "bachelor",
        experienceLevel: "mid",
        workEnvironment: ["office", "remote", "hybrid"],
        salaryRange: "senior"
    },
    {
        id: 9,
        title: "Teacher/Educator",
        category: "Education",
        match: 0,
        description: "Teachers educate students in various subjects and grade levels, developing lesson plans and assessing student progress.",
        salary: "$45,000 - $85,000",
        growth: "4% (As fast as average)",
        education: "Bachelor's in Education or related field",
        skills: ["Communication", "Leadership", "Creativity", "Problem Solving", "Patience"],
        interests: ["Education", "Mentoring", "Subject Matter"],
        minEducation: "bachelor",
        experienceLevel: "entry",
        workEnvironment: ["field"],
        salaryRange: "entry"
    },
    {
        id: 10,
        title: "Sales Manager",
        category: "Sales",
        match: 0,
        description: "Sales managers direct organizations' sales teams, setting goals, analyzing data, and developing training programs.",
        salary: "$70,000 - $150,000+",
        growth: "5% (As fast as average)",
        education: "Bachelor's in Business, Marketing, or related field",
        skills: ["Leadership", "Communication", "Sales", "Strategy", "Analytics"],
        interests: ["Sales", "Business", "Management", "Communication"],
        minEducation: "bachelor",
        experienceLevel: "mid",
        workEnvironment: ["office", "field"],
        salaryRange: "mid"
    }
];


// Interests and skills data
const interests = [
    "Technology", "Healthcare", "Business", "Education", "Arts", 
    "Science", "Engineering", "Marketing", "Finance", "Design",
    "Writing", "Research", "Management", "Sales", "Analytics",
    "Psychology", "Mathematics", "Problem Solving", "Creativity", "Strategy"
];

const skills = [
    "Programming", "Data Analysis", "Project Management", "Communication", 
    "Problem Solving", "Leadership", "Creativity", "Critical Thinking",
    "Teamwork", "Time Management", "Public Speaking", "Writing",
    "Research", "Design", "Marketing", "Sales", "Customer Service",
    "Analytics", "Strategy", "Technical Skills", "Interpersonal Skills"
];
